### ISSUE TITLE
Error: no implicit conversion of Fixnum into Hash at /opt/boxen/repo/shared/seil/manifests/bind.pp:9

### ISSUE THREAD

**Issue by charle5** [boxen/puppet-seil#2]
os x 10.9.5 (fresh install + update)
puppetfile:
`github "seil", "1.0.2"`

anything else i can provide to help debug this, just let me know.

**Comment by bryankennedy** [comment]
@llwt - That fix didn't work for me. I'm seeing the same error. It's odd, because I've had this working in my manifest for a while now and it just stopped working all of a sudden, when running on a new computer.

**Comment by bryankennedy** [comment]
Woops, ignore my previous comment. @llwt, your fix did work for me. I just needed to apply it to my second bind instance. Thanks for posting that.
