### ISSUE TITLE
Modify module to accept version as a Hiera variable

### ISSUE THREAD

**Issue by bryankennedy** [boxen/puppet-seil#8]
Is there a way to define the specified version of Seil you'd like to install? I don't seem to be able to override the seil::config::version value using hiera or any other method. I'm sure I'm just missing something obvious about Puppet.

**Comment by bryankennedy** [comment]
I just manually made a change and posted a PR here:
https://github.com/boxen/puppet-seil/pull/9

**Comment by smh** [comment]
I'm sure there is a way of doing this, but I'm no master of puppet or boxen, so I just followed how a couple of other modules did this. I'm happy to take a pull request if you'd like to make the version configurable. I think there are boxen modules that do it that way too.

**Comment by bryankennedy** [comment]
Yes, there are...now I just need to remember where I've seen it. I'll do some looking and see if I can patch together a PR.

**Comment by jacobbednarz** [comment]
Fixed in #9
